print("\n#############################\n")
print("#                           #\n")
print("#       BIMA SANJAYA        #\n")
print("#       2210817210008       #\n")
print("#                           #\n")
print("#############################\n")