nama=input("Nama                     : ")
nim=input("NIM                      : ")
k=input("Kelas Paralel            : ")
ttl=input("Tempat/Tanggal Lahir     : ")
alamat=input("Alamat                   : ")
h=input("Hobby                    : ")
hp=input("No. HP                   : ")
print("\nNama                     : ",nama)
print("NIM                      : ",nim)
print("Kelas Paralel            : ",k)
print("Tempat/Tanggal Lahir     : ",ttl)
print("Alamat                   : ",alamat)
print("Hobby                    : ",h)
print("No. HP                   : ",hp)