print("Test case ke 1:")
a=input("Masukkan Nilai Pertama : ")
b=input("Masukkan Nilai Kedua : ")
h1=float(a)+float(b)
print("Hasil dari penjumlahan nilai pertama \"",a,"\" dan nilai kedua \"",b,"\" adalah \"",h1,"\"")
print("\nTest case ke 2:")
a=input("Masukkan Nilai Pertama : ")
b=input("Masukkan Nilai Kedua : ")
h2=float(a)+float(b)
print("Hasil dari penjumlahan nilai pertama \"",a,"\" dan nilai kedua \"",b,"\" adalah \"",h2,"\"")